RE_TAG_DEFINITIONS = {
    "ACTIVITY-ACTOR-RECEIVER": 0,
    "ACTIVITY-ACTOR-PERFORMER": 1,
    "ACTIVITY-ACTIVITYDATA": 2,
    "ACTIVITY-ACTIVITY-PARENT": 3,
    "ACTIVITY-SPECIFICATION-REASON": 4,
    "ACTIVITY-SPECIFICATION-STATE": 5, # If something has a certain state or condition in APRV Mode
    "ACTIVITY-SPECIFICATION-IDENTIFICATION": 6, # Identify the activity alias, is, the
    "ACTIVITY-SPECIFICATION-FREQUENCY": 7, # Frequency of the activity
    "ACTIVITY-SPECIFICATION-QUANTITY": 8, # Quantity of the activity
    "ACTIVITY-SPECIFICATION-TIME": 9, # When something is done
    "ACTIVITY-SPECIFICATION-DURATION": 10, # How long something is done
    "ACTIVITY-SPECIFICATION-LOCATION": 11, # Where or in which direction or area
    "ACTIVITY-SPECIFICATION-DESCRIPTION": 12, # How is something done, further described
    "ACTIVITY-SPECIFICATION-INCLUDING": 13,
    "ACTIVITY-SPECIFICATION-ADDITIONAL": 14,
    "ACTIVITY-GUARD-DEADLINE": 15,
    "ACTIVITY-GUARD-EXACT": 16,
    "ACTIVITY-GUARD-LARGER": 17,
    "ACTIVITY-GUARD-SMALLER": 18,
    "ACTIVITY-GUARD-VALID": 19,
    "ACTIVITY-PURPOSE-OUTCOME-REASON": 20, # Reason for doing the activity (because, because maybe)
    "ACTIVITY-PURPOSE-OUTCOME-PURPOSE": 21, # Goal or desired outcome of an action
    "ACTIVITY-RELATION-DIRECT-CONDITION": 22,
    "ACTIVITY-RELATION-DIRECT-RESPONSE": 23,
    "ACTIVITY-RELATION-DIRECT-CONDITION-RESPONSE": 24,
    "ACTIVITY-RELATION-INDIRECT-CONNECT": 25, # Connect two activities
    "ACTIVITY-RELATION-INDIRECT-FROM": 26,
    "ACTIVITY-RELATION-INDIRECT-TO": 27,
}