#Training args
model_name_or_path: HiTZ/GoLLIE-34B
cache_dir: /work3/s213709
torch_dtype: bfloat16
use_lora: false
quantization: 4
quantization_inference: 4
gradient_checkpointing: true
force_auto_device_map: true
# max_memory_MB: 80000
use_flash_attention: true

# dataset arguments
dataset_dir:
  /zhome/06/4/166098/GoLLIEProcessExtraction/data/processed_w_examples
validation_tasks:
  - medicalguideline.ner
  - medicalguideline.re
test_tasks:
  - medicalguideline.ner
  - medicalguideline.re
max_examples_per_task_train: 30000
max_examples_per_task_val: 5000
max_examples_per_task_test: null
max_seq_length: 2688
generation_max_length: 2688
ignore_pad_token_for_loss: true
prompt_loss_weight: 0.0

# checkpoint settings
output_dir: /zhome/06/4/166098/GoLLIEProcessExtraction/results/GoLLIE+-34b_CodeLLaMA
overwrite_output_dir: true
load_best_model_at_end: false
save_strategy: "epoch"
save_steps: 1000
save_total_limit: 999

# evaluation
do_train: false
do_eval: false
do_predict: true
evaluation_strategy: "epoch"
eval_steps: 500
eval_delay: 0
predict_with_generate: true
evaluate_all_checkpoints: false

# batch size
per_device_train_batch_size: 4
per_device_eval_batch_size: 2
gradient_accumulation_steps: 4 # 2 FOR 2 GPUs, 4 FOR 1 GPU (32 efective batch size)
generation_num_beams: 1

# optimizer settings
optim: adamw_torch_fused
learning_rate: 0.0003
weight_decay: 0.0
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.03
adam_epsilon: 1e-7

# lora settings
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
  - all

# reporting
logging_strategy: steps
logging_first_step: true
logging_steps: 25
report_to: wandb
run_name: "GoLLIE+-34b_CodeLLaMA"
disable_tqdm: false

# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: true
fp16: false
torch_compile: false
ddp_find_unused_parameters: false
